export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_CHECK_SUCCESS = "AUTH_CHECK_SUCCESS";
export const AUTH_CHECK_ERROR = "AUTH_CHECK_ERROR";

export const OPENVACANCY = "OPENVACANCY";
export const OPENVACANCY_SUCCESS = "OPENVACANCY_SUCCESS";
export const OPENVACANCY_ERROR = "OPENVACANCY_ERROR";
