export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_CHECK_SUCCESS = "AUTH_CHECK_SUCCESS";
export const AUTH_CHECK_ERROR = "AUTH_CHECK_ERROR";

export const OPENVACANCY = "OPENVACANCY";
export const OPENVACANCY_SUCCESS = "OPENVACANCY_SUCCESS";
export const OPENVACANCY_ERROR = "OPENVACANCY_ERROR";

export const GETVACANCY = "GETVACANCY";
export const GETVACANCY_SUCCESS = "GETVACANCY_SUCCESS";
export const GETVACANCY_ERROR = "GETVACANCY_ERROR";

export const GET_APLICATION = "GET_APLICATION";
export const GET_APLICATION_SUCCESS = "GET_APLICATION_SUCCESS";
export const GET_APLICATION_ERROR = "GET_APLICATION_ERROR";
